output_dir: {{ output_dir }}

dataset:
  class: biomedical
  path: {{ dataset_path }}
  include_factgraph: yes
  files: ['train1.txt', 'train2.txt', 'valid.txt', 'test.txt']

task:
  class: KnowledgeGraphCompletionBiomed
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32, 32, 32]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    dependent: yes
    symmetric: no
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 0.5
  sample_weight: no
  heterogeneous_negative: yes
  heterogeneous_evaluation: yes
  full_batch_eval: yes
  train2_in_factgraph: no

optimizer:
  class: Adam
  lr: 1.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: {{ batch_size }}

train:
  num_epoch: {{ num_epoch }}

metric: mrr
